version: '2'

services:

  postgres:
    build: tools/docker-compose-assets/postgres
    network_mode: 'bridge'
    ports:
      - '5400:5432'
    environment:
      - POSTGRES_PASSWORD=ntb
      - POSTGRES_USER=ntb
      - POSTGRES_DB=ntb
    logging:
      options:
        max-size: "10k"

  api:
    build: .
    network_mode: 'bridge'
    ports:
      - '3000'
      - '9229:9229'
    volumes:
      - .:/build
    working_dir: /build
    links:
      - postgres
    depends_on:
      - postgres
    logging:
      options:
        max-size: "500k"
    environment:
      - NODE_ENV=development
      - NPM_CONFIG_LOGLEVEL=info
      - NPM_CONFIG_PROGRESS=false
      - NPM_CONFIG_SPIN=false
      - VIRTUAL_HOST=api.ntb.local
      - VIRTUAL_PORT=3000
      - VIRTUAL_PATH=/
    command: /build/tools/docker-compose-assets/service-api-init.sh
    extra_hosts:
      - "api.dnt.local:${DOCKER_IP}"
      - "postgres.ntb.local:${DOCKER_IP}"

  admin-server:
    build: .
    network_mode: 'bridge'
    ports:
      - '8080'
      - '9228:9229'
    volumes:
      - .:/build
    working_dir: /build
    links:
      - postgres
      - admin-redis
      - admin-client
    depends_on:
      - postgres
      - admin-redis
    logging:
      options:
        max-size: "500k"
    environment:
      - NODE_ENV=development

      # Configuration for docker-proxy
      - VIRTUAL_HOST=admin.ntb.local
      - VIRTUAL_PORT=8080
    command: /build/tools/docker-compose-assets/service-admin-server-init.sh
    extra_hosts:
      - "api.dnt.local:${DOCKER_IP}"
      - "postgres.ntb.local:${DOCKER_IP}"

  admin-client:
    build: .
    network_mode: 'bridge'
    ports:
      - '3000'
    volumes:
      - .:/build
    working_dir: /build
    logging:
      options:
        max-size: "500k"
    environment:
      - NODE_ENV=development

      # Configuration for docker-proxy
      - VIRTUAL_HOST=admin-assets.ntb.local
      - VIRTUAL_PORT=3000
    command: /build/tools/docker-compose-assets/service-admin-client-init.sh

  admin-redis:
    image: redis:4
    network_mode: 'bridge'
    logging:
      options:
        max-size: "10k"

  docs-server:
    build: .
    network_mode: 'bridge'
    ports:
      - '8080'
      - '9227:9229'
    volumes:
      - .:/build
    working_dir: /build
    links:
      - postgres
      - docs-client
    depends_on:
      - postgres
    logging:
      options:
        max-size: "500k"
    environment:
      - NODE_ENV=development

      # Configuration for docker-proxy
      - VIRTUAL_HOST=docs.ntb.local
      - VIRTUAL_PORT=8080
    command: /build/tools/docker-compose-assets/service-docs-server-init.sh
    extra_hosts:
      - "api.dnt.local:${DOCKER_IP}"
      - "postgres.ntb.local:${DOCKER_IP}"

  docs-client:
    build: .
    network_mode: 'bridge'
    ports:
      - '3000'
    volumes:
      - .:/build
    working_dir: /build
    logging:
      options:
        max-size: "500k"
    environment:
      - NODE_ENV=development

      # Configuration for docker-proxy
      - VIRTUAL_HOST=docs-assets.ntb.local
      - VIRTUAL_PORT=3000
    command: /build/tools/docker-compose-assets/service-docs-client-init.sh
