version: '2'

services:
  api:
    build: .
    network_mode: 'bridge'
    ports:
      - '3000'
      - '9229:9229'
    volumes:
      - .:/build
    working_dir: /build
    links:
      - postgres
    depends_on:
      - postgres
    logging:
      options:
        max-size: "500k"
    environment:
      - NODE_ENV=development
      - NPM_CONFIG_LOGLEVEL=info
      - NPM_CONFIG_PROGRESS=false
      - NPM_CONFIG_SPIN=false
      - VIRTUAL_HOST=api.ntb.local
      - VIRTUAL_PORT=3000
      - VIRTUAL_PATH=/
    command: /build/tools/docker-compose-assets/service-api-init.sh
    # command: nodemon -w services/api --w shared --w settings-dev.json --inspect=0.0.0.0:9229 services/api/index.js
    extra_hosts:
      - "api.dnt.local:${DOCKER_IP}"

  postgres:
    build: tools/docker-compose-assets/postgres
    network_mode: 'bridge'
    ports:
      - '5400:5432'
    environment:
      - POSTGRES_PASSWORD=ntb
      - POSTGRES_USER=ntb
      - POSTGRES_DB=ntb
    logging:
      options:
        max-size: "10k"
