version: 2
jobs:
  build-image:
    docker:
      # specify the version you desire here
      - image: google/cloud-sdk:latest

    working_directory: ~/repo

    steps:
      - run:
          name: authenticate with gcloud
          command: |
            echo $GCLOUD_DOCKER_CREDENTIALS > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json

      # if authentication succeeded - checkout code
      - checkout

      # starts a remote docker environment to run docker commands
      - setup_remote_docker

      - run:
          name: build ntb docker image and push to gcloud and push image to GCR
          command: |
            gcloud auth configure-docker --quiet
            TAG=ntb-${CIRCLE_SHA1:0:9}
            docker build -t ntb .
            docker tag ntb eu.gcr.io/dnt-docker-registry-public/ntb:latest
            docker tag ntb eu.gcr.io/dnt-docker-registry-public/ntb:$TAG
            docker push eu.gcr.io/dnt-docker-registry-public/ntb:latest
            docker push eu.gcr.io/dnt-docker-registry-public/ntb:$TAG
      
      - run:
           name: notify slack on failure
           when: on_fail
           command: |
             chmod +x .circleci/notify-slack.sh
             ./.circleci/notify-slack.sh NTB build-and-publish false
      - run:
           name: notify slack on sucess
           when: on_success
           command: |
             chmod +x .circleci/notify-slack.sh
             ./.circleci/notify-slack.sh NTB build-and-publish true      

  deploy-to-dev:
    docker:
      - image: praqma/helmsman:v1.3.0-helm-v2.8.1
    steps:
      - checkout
      - run:
          name: run helmsman
          command: |
            export IMAGE_TAG=ntb-${CIRCLE_SHA1:0:9}
            helmsman --debug --apply -f .circleci/helmsman-dev-deployment.toml

      - run:
           name: notify slack on failure
           when: on_fail
           command: |
             chmod +x .circleci/notify-slack.sh
             ./.circleci/notify-slack.sh NTB build-and-publish false
      - run:
           name: notify slack on sucess
           when: on_success
           command: |
             chmod +x .circleci/notify-slack.sh
             ./.circleci/notify-slack.sh NTB build-and-publish true

  deploy-to-beta:
    docker:
      - image: praqma/helmsman:v1.3.0-helm-v2.8.1
    steps:
      - checkout
      - run:
          name: run helmsman
          command: |
            helmsman --debug --apply -f .circleci/helmsman-beta-deployment.toml
      - run:
           name: notify slack on failure
           when: on_fail
           command: |
             chmod +x .circleci/notify-slack.sh
             ./.circleci/notify-slack.sh NTB build-and-publish false
      - run:
           name: notify slack on sucess
           when: on_success
           command: |
             chmod +x .circleci/notify-slack.sh
             ./.circleci/notify-slack.sh NTB build-and-publish true

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build-image:
          context: dnt-k8s-dev-beta
          filters:
            branches:
              only:
                - master
      - deploy-to-dev:
          requires:
            - build-image
          context: dnt-k8s-dev-beta
          filters:
            branches:
              only:
                - master
      - deploy-to-beta:
          context: dnt-k8s-dev-beta
          filters:
            branches:
              only:
                - deploy-beta
