# Default values for the NTB Helm Chart.
# This is a YAML-formatted file.

# Declare variables with default values to be passed into your templates.
# To override them, you need to (a) either adjust this file, or (b) provide your own values file,
# which overrides the values found here.

containerName: ntb

image:
  name: "eu.gcr.io/dnt-docker-registry-public/ntb"
  tag: "ntb-4cb8a13a1"
  imagePullPolicy: "Always"

environment:
  NODE_ENV: "production"
  LEGACY_MONGO_DB_URI: ""
  LEGACY_MONGO_DB_NAME: ""
  DB_DIALECT: "postgres"
  DB_HOST: "localhost"
  DB_PORT: "5432"
  DB_USER: ""
  DB_PASSWORD: ""
  DB_NAME: ""
  DB_POOL_MIN: 1
  DB_POOL_MAX: 5
  DB_MIN_QUERY_TIME_FOR_LOGGING: 30

  SERVICES_ADMIN_PORT: 8080
  SERVICES_ADMIN_SENTRY_DSN: null
  SERVICES_ADMIN_GA_CODE: null
  SERVICES_ADMIN_GTM_CODE: null
  SERVICES_ADMIN_OAUTH_CLIENT_ID: null
  SERVICES_ADMIN_OAUTH_CLIENT_SECRET: null
  SERVICES_ADMIN_OAUTH_DOMAIN: null
  SERVICES_ADMIN_SHERPA_API_DOMAIN: null
  SERVICES_ADMIN_REDIS_HOSTNAME: "redis"
  SERVICES_ADMIN_REDIS_PORT: 6379

  SERVICES_DOCS_PORT: 8080
  SERVICES_DOCS_SENTRY_DSN: null
  SERVICES_DOCS_GA_CODE: null
  SERVICES_DOCS_GTM_CODE: null

  INSTANCE_CONNECTION_NAME: ""

service:
  api:
    name: api
    type: ClusterIP
    port: 3000

  docs:
    name: docs
    type: ClusterIP
    port: 8080


ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: true

  hosts:
     - host: ntb-api.beta.dnt.org
       paths:
         - path: /
           serviceName: ntb-beta-api
           servicePort: 3000
     - host: ntb-docs.beta.dnt.org
       paths:
         - path: /
           serviceName: ntb-beta-docs
           servicePort: 8080

  tls:
    - secretName: beta-dnt-org-tls
      hosts:
        - ntb-api.beta.dnt.org
        - ntb-docs.beta.dnt.org


cert:
  enabled: false
  issuer: "letsencrypt-production"


nodeSelector:
  machineType: high-mem


resources:
  cloudsqlProxy:
      requests:
        cpu: 70m
        memory: 200Mi
