# Default values for the NTB Helm Chart.
# This is a YAML-formatted file.

# Declare variables with default values to be passed into your templates.
# To override them, you need to (a) either adjust this file, or (b) provide your own values file,
# which overrides the values found here.

containerName: ntb

image:
  name: "eu.gcr.io/dnt-docker-registry-public/ntb"
  tag: "latest"
  imagePullPolicy: "Always"

environment:
  NODE_ENV: "production"
  LEGACY_MONGO_DB_URI: ""
  LEGACY_MONGO_DB_NAME: ""
  DB_DIALECT: "postgres"
  DB_HOST: "localhost"
  DB_PORT: "5432"
  DB_USER: ""
  DB_PASSWORD: ""
  DB_NAME: ""
  DB_POOL_MIN: 1
  DB_POOL_MAX: 5
  DB_MIN_QUERY_TIME_FOR_LOGGING: 30

  SERVICES_ADMIN_PORT: 8080
  SERVICES_ADMIN_SENTRY_DSN: null
  SERVICES_ADMIN_GA_CODE: null
  SERVICES_ADMIN_GTM_CODE: null
  SERVICES_ADMIN_OAUTH_CLIENT_ID: null
  SERVICES_ADMIN_OAUTH_CLIENT_SECRET: null
  SERVICES_ADMIN_OAUTH_DOMAIN: null
  SERVICES_ADMIN_SHERPA_API_DOMAIN: null
  SERVICES_ADMIN_REDIS_HOSTNAME: "redis"
  SERVICES_ADMIN_REDIS_PORT: 6379

  SERVICES_DOCS_PORT: 8080
  SERVICES_DOCS_SENTRY_DSN: null
  SERVICES_DOCS_GA_CODE: null
  SERVICES_DOCS_GTM_CODE: null

  INSTANCE_CONNECTION_NAME: "something"

cronJobs:
  # see https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/
  - name: cron-01
    schedule: 0,29 * * * *
    startingDeadlineSeconds: 400
    concurrencyPolicy: Replace # or Forbid or Allow
    cloudsqlProxy: true # add a cloudsql proxy container
    command: node cronjobs/01-harvest-legacy-ntb-pictures/index.js
  - name: cron-02
    schedule: 1,30 * * * *
    startingDeadlineSeconds: 400
    concurrencyPolicy: Replace # or Forbid or Allow
    cloudsqlProxy: true # add a cloudsql proxy container
    command: node cronjobs/02-harvest-legacy-ntb-areas/index.js
  - name: cron-03
    schedule: 2,32 * * * *
    startingDeadlineSeconds: 400
    concurrencyPolicy: Replace # or Forbid or Allow
    cloudsqlProxy: true # add a cloudsql proxy container
    command: node cronjobs/03-harvest-legacy-ntb-groups/index.js
  - name: cron-04
    schedule: 3,33 * * * *
    startingDeadlineSeconds: 400
    concurrencyPolicy: Replace # or Forbid or Allow
    cloudsqlProxy: true # add a cloudsql proxy container
    command: node cronjobs/04-harvest-legacy-ntb-cabins/index.js
  - name: cron-05
    schedule: 4,34 * * * *
    startingDeadlineSeconds: 400
    concurrencyPolicy: Replace # or Forbid or Allow
    cloudsqlProxy: true # add a cloudsql proxy container
    command: node cronjobs/05-harvest-legacy-ntb-pois/index.js
  - name: cron-06
    schedule: 5,35 * * * *
    startingDeadlineSeconds: 400
    concurrencyPolicy: Replace # or Forbid or Allow
    cloudsqlProxy: true # add a cloudsql proxy container
    command: node cronjobs/06-harvest-legacy-ntb-routes/index.js
  - name: cron-07
    schedule: 6,36 * * * *
    startingDeadlineSeconds: 400
    concurrencyPolicy: Replace # or Forbid or Allow
    cloudsqlProxy: true # add a cloudsql proxy container
    command: node cronjobs/07-harvest-legacy-ntb-trips/index.js
  - name: cron-08
    schedule: 7,37 * * * *
    startingDeadlineSeconds: 400
    concurrencyPolicy: Replace # or Forbid or Allow
    cloudsqlProxy: true # add a cloudsql proxy container
    command: node cronjobs/08-harvest-legacy-ntb-lists/index.js
  - name: cron-09
    schedule: 0 1 1 * * # Once every month
    startingDeadlineSeconds: 400
    concurrencyPolicy: Replace # or Forbid or Allow
    cloudsqlProxy: true # add a cloudsql proxy container
    command: node cronjobs/09-harvest-counties-municipalities/index.js
  - name: cron-10
    schedule: 0 1 2 * * # Once every month
    startingDeadlineSeconds: 400
    concurrencyPolicy: Replace # or Forbid or Allow
    cloudsqlProxy: true # add a cloudsql proxy container
    command: node cronjobs/10-harvest-route-geometry-wfs-data/index.js
  - name: cron-11
    schedule: 0 2 * * * # 02:00 every day
    startingDeadlineSeconds: 400
    concurrencyPolicy: Replace # or Forbid or Allow
    cloudsqlProxy: true # add a cloudsql proxy container
    command: node cronjobs/11-process-ski-route-segments/index.js
  - name: cron-12
    schedule: 0 3 * * * # 03:00 every day
    startingDeadlineSeconds: 400
    concurrencyPolicy: Replace # or Forbid or Allow
    cloudsqlProxy: true # add a cloudsql proxy container
    command: node cronjobs/12-process-bike-route-segments/index.js
  - name: cron-13
    schedule: 0 4 * * * # 04:00 every day
    startingDeadlineSeconds: 400
    concurrencyPolicy: Replace # or Forbid or Allow
    cloudsqlProxy: true # add a cloudsql proxy container
    command: node cronjobs/13-process-other-route-segments/index.js
  - name: cron-14
    schedule: 30 4 * * * # 04:30 every day
    startingDeadlineSeconds: 400
    concurrencyPolicy: Replace # or Forbid or Allow
    cloudsqlProxy: true # add a cloudsql proxy container
    command: node cronjobs/14-process-foot-route-segments/index.js
  - name: cron-15
    schedule: 30 1 * * * # 01:30 every day
    startingDeadlineSeconds: 400
    concurrencyPolicy: Replace # or Forbid or Allow
    cloudsqlProxy: true # add a cloudsql proxy container
    command: node cronjobs/15-harvest-hazard-regions/index.js
  - name: cron-16
    schedule: 4,14,24,34,44,54 * * * * # Every 10 minutes
    startingDeadlineSeconds: 400
    concurrencyPolicy: Replace # or Forbid or Allow
    cloudsqlProxy: true # add a cloudsql proxy container
    command: node cronjobs/16-process-geometry-intersections/index.js
  - name: cron-17
    schedule: 9,19,29,39,49,59 * * * * # Every 10 minutes
    startingDeadlineSeconds: 400
    concurrencyPolicy: Replace # or Forbid or Allow
    cloudsqlProxy: true # add a cloudsql proxy container
    command: node cronjobs/17-process-geometry-distance-relation/index.js

service:
  api:
    name: api
    type: ClusterIP
    port: 3000

  docs:
    name: docs
    type: ClusterIP
    port: 8080


ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx

  hosts:
     - host: ntb-api.dev.dnt.org
       paths:
         - path: /
           serviceName: ntb-api
           servicePort: 3000
     - host: ntb-docs.dev.dnt.org
       paths:
         - path: /
           serviceName: ntb-docs
           servicePort: 8080

  tls:
    - secretName: dev-beta-dnt-org-tls
      hosts:
        - ntb-api.dev.dnt.org
        - ntb-docs.dev.dnt.org


cert:
  enabled: false
  issuer: "letsencrypt-production"

resources:
  cloudsqlProxy:
      requests:
        cpu: 70m
        memory: 200Mi
